name: "KLC Compliance Check"

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # and if relevant files have changed, including this GitHub action files
  push:
    branches: [ "main" ]
    paths: 
      - "SimPanel.pretty/*.kicad_mod"
      - ".github/workflows/kicad-klc-check.yml"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "SimPanel.pretty/*.kicad_mod"
      - ".github/workflows/kicad-klc-check.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  KLC_ComplianceCheck:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10.11'

      # We use this to limit KLC checking to only changed files
      - id: footprint_files
        name: Get Changed Files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      
      - name: Run KiCad KLC Footprint Check
        run: |
            readarray -t changed_files <<<"$(jq -r '.[]' <<<'${{ steps.footprint_files.outputs.added_modified }}')"
            for changed_file in ${changed_files[@]}; do
              if [[ ${changed_file} == *.kicad_mod ]]; then
                python ./library-utils/klc-check/check_footprint.py ./${changed_file} -vv
              fi
            done