name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10.11'

      - name: Run KiCad KLC Footprint Check
        run: python  ./library-utils\klc-check\check_footprint.py ./SimPanel.pretty/*
